[package]
name = "app"
version = "0.1.0"
authors = ["skobochka"]
edition = "2018"

[dependencies]
common = { path = "../common" }
tokio = { version = "0.2.21", features = ["macros"] }
hyper = "0.13.5"
http-body = "0.3.1"
