[package]
name = "common"
version = "0.2.2"
authors = ["skobochka"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
hyper = "0.13"
hyper-tls = "0.4"
http-body = "0.3"
tokio = "0.2"
