[package]
name = "common"
version = "0.7.0"
authors = ["skobochka"]
edition = "2018"

[dependencies]
lru = "^0.5"
pest = "^2.1"
pest_derive = "^2.1"
futures = "^0.3"
hyper = "0.13"
hyper-tls = "^0.4"
http-body = "^0.3"
tokio = "^0.2"
serde = "^1.0"
serde_derive = "^1.0"
